### ISSUE TITLE
[DRF] Schema not generated for custom ViewSet actions

### ISSUE THREAD

**Issue by hexedit** [carltongibson/django-filter#1041]
Filter:
```python
class MyModelFilter(filters.FilterSet):
    class Meta:
        model = MyModel
        fields = ['int_filter', 'str_filter']
```
ViewSet:
```python
class MyModelView(ModelViewSet):
    queryset = MyModel.objects.all()
    serializer_class = MyModelSerializer
    filterset_class = MyModelFilter

    @action(detail=False)
    def count(self):
        queryset = self.filter_queryset(self.get_queryset())
        return Response({'count': queryset.count()})
```
Generated schema:
```yaml
paths:
  /mymodel/:
    get:
      operationId: mymodel_list
      parameters:
      - in: query
        name: int_filter
        schema:
          description: ''
          title: ''
          type: number
      - in: query
        name: str_filter
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - mymodel
  /mymodel/count/:
    get:
      operationId: mymodel_count
      tags:
      - mymodel
  /mymodel/{id}/:
    get:
      operationId: mymodel_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this mymodel.
          title: ID
          type: integer
      - in: query
        name: int_filter
        schema:
          description: ''
          title: ''
          type: number
      - in: query
        name: str_filter
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - mymodel
```
Filtering on `count` works as expected but parameters are not generated in schema (schema is generated by `rest_framework.schemas.get_schema_view`)
