### ISSUE TITLE
OrderingFilter causing Parser error: unknown tag when using OpenAPI schema

### ISSUE THREAD

**Issue by dennishylau** [carltongibson/django-filter#1135]
Specifically, the `description` field generated was problematic.
e.g.
```
/api/{version}/business/brand/:
    get:
      operationId: listBrands
      parameters:
      ...
      - name: ordering
        required: false
        in: query
        description: &id001 !!python/object/apply:django.utils.functional._lazy_proxy_unpickle
        - !!python/name:django.utils.translation.gettext ''
        - !!python/tuple
          - Ordering
        - {}
        - !!python/name:builtins.str ''
        schema:
          type: string
```

So when swagger-ui is loading the schema, this shows up

```
Errors
Hide
 
Parser error on line 638
unknown tag !<tag:yaml.org,2002:python/name:django.utils.translation.gettext>
```

To get around this, I must set the label attribute when 

```
ordering = OrderingFilter(fields=(...), label='Hello World')
```

Thank you.
