### ISSUE TITLE
Multiple Choice fields don't generate the proper schema

### ISSUE THREAD

**Issue by SafaAlfulaij** [carltongibson/django-filter#1297]
## FilterSet
```python
class ObjectsFilterSet(FilterSet):
    type = MultipleChoiceFilter(
        field_name='type',
        label='Type of object',
        choices=(
            ('A', 'A'),
            ('B', 'B'),
            ('C', 'C')
        ),
    )
```

## Current result
```yaml
      - name: type
        required: false
        in: query
        description: Type of object
        schema:
          type: string
          enum:
            - A
            - B
            - C
```

## Expected result

```yaml
      - name: type
        required: false
        in: query
        description: Type of object
        schema:
          type: array
          items:
            type: string
            enum:
            - A
            - B
            - C
```

## Proposed solution
Fix https://github.com/carltongibson/django-filter/blob/master/django_filters/rest_framework/backends.py#L168:
```python
            if field.extra and 'choices' in field.extra:
                parameter['schema']['enum'] = [c[0] for c in field.extra['choices']]

                if isinstance(field, MultipleChoiceFilter):
                    parameter['schema'] = {
                        'type': 'array',
                        'items': parameter['schema']
                    }
```
