### ISSUE TITLE
Support for true/false values for boolean field?

### ISSUE THREAD

**Issue by dmitry-saritasa** [carltongibson/django-filter#714]
Support for true/false as for the values of a boolean filter field is not working?

```
{{api_url}}/api/v1/games/?limit=10&offset=0&is_published=true
{{api_url}}/api/v1/games/?limit=10&offset=0&is_published=false
```

### the filter is defined as

```
is_published = BooleanFilter(name='versions__is_published')
```

### my swagger specification defines the filter as bool

```
get:
  summary: Get list of games
  operationId: getGamesList
  parameters:
    - $ref: '../../parameters.yaml#/Offset'
    - $ref: '../../parameters.yaml#/Limit'
    - $ref: '../../parameters.yaml#/PlatformsFilter'
    - $ref: '../../parameters.yaml#/DevelopersFilter'
    - $ref: '../../parameters.yaml#/GenresFilter'
    - $ref: '../../parameters.yaml#/AgesFilter'
    - $ref: '../../parameters.yaml#/SearchFilter'
    - $ref: '../../parameters.yaml#/Order'
    - name: is_published
      in: query
      type: boolean
      required: false
      default: true
```
unfortunately **swagger** used 'true/false' value as get parameters, while django_filter expects uppercase, as "True/False"

![image](https://cloud.githubusercontent.com/assets/1747653/26073943/1625a47a-3965-11e7-8662-6d8b4f636870.png)
